<?php
/**
 * Custom template to support MageSuite products carousel as widget's template.
 */

use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
?>

<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php if ($block->getTitle()) : ?>
        <?= /* @noEscape */ $block->getLayout()->createBlock(
            \MageSuite\ContentConstructorFrontend\Block\Component::class,
            'carousels-headline-product-carousel' . uniqid(),
            [
                'data' => [
                    'section' => 'content',
                    'type' => 'headline',
                    'data' => [
                        'title' => __($block->getTitle()),
                        'container_mix' => '-widget cs-container--headline'
                    ]
                ],
            ]
        )->toHtml(); ?>
    <?php endif ?>

    <?php
    $items = $block->getProductCollection()->getItems();
    $productsId = [];

    foreach ($items as $item) {
        $productsId[] = $item->getEntityId();
    }
    ?>
    <?= /* @noEscape */ $block->getLayout()->createBlock(
        \MageSuite\ContentConstructorFrontend\Block\Component::class,
        '',
        [
            'data' => [
                'type' => 'product-carousel',
                'data' => [
                    'product_ids' => $productsId,
                    'container_mix' => '-widget',
                    'mix' => '--widget cs-products-carousel'
                ]
            ]
        ]
    )->toHtml();
    ?>
<?php endif;?>
