<?php
/**
 * Custom template to support MageSuite product teaser as widget's template.
 */

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $items = $block->getProductCollection()->getItems();
    $sku = array_shift($items)->getSku();
    if (!$sku) {
        return;
    }
    ?>
    <?php if ($block->getTitle()) : ?>
        <?= /* @noEscape */ $block->getLayout()->createBlock(
            \MageSuite\ContentConstructorFrontend\Block\Component::class,
            'carousels-headline-product-carousel' . uniqid(),
            [
                'data' => [
                    'section' => 'content',
                    'type' => 'headline',
                    'data' => [
                        'title' => __($block->getTitle()),
                        'container_mix' => '-widget cs-container--headline'
                    ]
                ],
            ]
        )->toHtml(); ?>
    <?php endif ?>

    <?= /* @noEscape */ $block->getLayout()->createBlock(
        \MageSuite\ContentConstructorFrontend\Block\Component::class,
        '',
        [
            'data' => [
                'type' => 'product-teaser',
                'data' => [
                    'sku' => $sku,
                    'container_mix' => '-widget'
                ]
            ]
        ]
    )->toHtml();
    ?>
<?php endif;?>
